### ISSUE TITLE
SX-UI & Stamp: cover images are cut

### ISSUE THREAD

**Issue by bonustrack** [snapshot-labs/stamp#172]
The cover image are too much cut, not sure if the issue come from Stamp or SX-UI, here is an example:
https://snapshotx.xyz/#/sn:0x0041ada9121061198b52ae28edeec8ace7c23f2ba8d66938c129af1a2245701c
This space use this image: https://twitter.com/ensdomains
We should see the full width of the image

**Comment by wa0x6e** [comment]
Stamp is working as expected, and returning the image given the params.

ENS Twitter profile is https://pbs.twimg.com/profile_banners/996321865311358976/1704332406/1500x500
Stamp can return the same with https://cdn.stamp.fyi/space-cover-sx/0x0041ada9121061198b52ae28edeec8ace7c23f2ba8d66938c129af1a2245701c?w=1500&h=500&cb=13db3b61626910b2

SX-UI image is cut now because it's using height 156, whereas the ENS image was made to be displayed with height 500

**Comment by bonustrack** [comment]
![Uploading Screenshot_20240614_215003_Chrome.jpg…]()

**Comment by bonustrack** [comment]
![Screenshot_20240614_215003_Chrome](https://github.com/snapshot-labs/stamp/assets/16245250/0ef3702c-dbeb-4b41-9b79-41df4327906f)

**Comment by wa0x6e** [comment]
See https://github.com/snapshot-labs/sx-monorepo/pull/404
